"""
compare_latent.py

Loads the latent coordinates generated by all configurations and plots them side-by-side
to compare the characteristics of the generated latent spaces.
"""
import numpy as np
import matplotlib.pyplot as plt
import os

def compare_latent_spaces():
    results_dir = "results_comparative"
    if not os.path.exists(results_dir):
        print(f"Error: {results_dir} not found.")
        return

    # Find all subdirectories in results_comparative
    config_dirs = [d for d in os.listdir(results_dir) if os.path.isdir(os.path.join(results_dir, d))]
    # Sort them alphabetically for consistency
    config_dirs.sort()
    
    if not config_dirs:
        print("No configurations found to compare.")
        return
        
    num_configs = len(config_dirs)
    cols = min(3, num_configs)
    rows = (num_configs + cols - 1) // cols
    
    fig, axes = plt.subplots(rows, cols, figsize=(6 * cols, 5 * rows))
    if num_configs == 1:
        axes = np.array([axes])
    axes = axes.flatten()
    
    labels = [chr(0x60 + i) for i in range(32)]
    
    for i, config_name in enumerate(config_dirs):
        ax = axes[i]
        latent_file = os.path.join(results_dir, config_name, "latent_coords.npy")
        
        if os.path.exists(latent_file):
            latent = np.load(latent_file)
            ax.scatter(latent[:, 0], latent[:, 1], c='blue', marker='o')
            
            # Annotate only every few points or make text smaller to reduce clutter
            for j in range(32):
                ax.annotate(f"{labels[j]}", (latent[j, 0], latent[j, 1]), 
                            fontsize=8, alpha=0.7, xytext=(3, 3), textcoords='offset points')
                            
            ax.set_title(f"Config: {config_name}")
            ax.set_xlabel("Latent Variable 1")
            ax.set_ylabel("Latent Variable 2")
            ax.grid(True, linestyle='--', alpha=0.6)
        else:
            ax.text(0.5, 0.5, "Data not found", ha='center', va='center')
            ax.set_title(f"Config: {config_name}")
            ax.axis('off')
            
    # Hide unused subplots
    for i in range(num_configs, len(axes)):
        axes[i].axis('off')
        
    plt.tight_layout()
    output_file = os.path.join(results_dir, "latent_space_comparison.png")
    plt.savefig(output_file)
    print(f"\nSaved final comparative latent space graph to {output_file}")
    plt.close()

if __name__ == "__main__":
    compare_latent_spaces()
